### ISSUE TITLE
Error status with lighting with dimmer 

### ISSUE THREAD

**Issue by olaquetal** [openwebnet/openwebnet-site#4]
Hi,
Thank you very much for your wonderful application.
I have a lightning with a dimmer (LG-003651).  I set it as a "normal" light.
I can turn it on and off, but sometimes I have the warning symbol "!" when it's on and I can't turn it off with the app.
Is there a specific type for dimmers ?
Thank you very much

**Comment by niqdev** [comment]
Hi, thanks for your interest in this project.

I suppose the warning symbol is due to some connectivity errors. When this happens, you should just try to refresh the screen (pull from top) to update the status of the lights.

About dimmers, you can see [this](https://github.com/openwebnet/openwebnet-android/issues/23) issue. At the bottom, I've linked an example. You basically need to create a custom device. The changes to add this functionality are not big, but I don't have time for it. You are more than happy to contribute to the project and open prs, and I can point you to what should be changed if you are interested.

I prefer to keep track of all the issues in a single place [here](https://github.com/openwebnet/openwebnet-android/issues), so I'll close this pr. Feel free to move the conversation to the other repository or open a new issue.
Thanks
